# Generated by Django 3.2.7 on 2021-10-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_foods', '0005_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
