# Generated by Django 3.2.8 on 2021-10-17 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='')),
                ('user', models.CharField(max_length=100)),
                ('caption', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default='')),
                ('no_of_like', models.IntegerField(default=0)),
                ('rate', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
